language: python

python: "3.4"

script: make build

before_deploy: pip install awscli

deploy:
  provider: script
  script: aws s3 mv --recursive dist s3://mirror.cs50.net/pypi/cli50/
  skip_cleanup: true
  on:
    all_branches: true
