language: python
python: '3.4'
branches:
  except: "/^v\\d/"
install: true
script: true
deploy:
- provider: script
  script: 'curl --fail --data "{ \"tag_name\": \"v$(python setup.py --version)\",
    \"target_commitish\": \"$TRAVIS_COMMIT\", \"name\": \"v$(python setup.py --version)\"
    }" --user kzidanebot:$GITHUB_TOKEN https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases'
  on:
    branch: develop
